version: '3.1'

services:
  python:
    build: .
    restart: always
    container_name: python_project
    depends_on:
      - redis

  redis:
    image: redis
    restart: always
    container_name: redis_db
    volumes:
      - ./docker_volumes/redis_data:/data
    ports:
      - "6379:6379"
